server:
  port: 8080
  app_name: erp
  secret_key: secret_key

database:
  type: postgres
  host: localhost
  port: 5432
  user: postgres
  password: balakutak
  name: erp_db

email:
  server: sandbox.smtp.mailtrap.io
  port: 2525
  username: 60f2f52a685efb
  password: 0261f8e473e3a0
  from: support@ametory.id