package account

var GenericChartOfAccount = []AccountModel{
	{
		Name:             "Kas Kecil",
		Code:             "11001",
		Type:             ASSET,
		Category:         "Cash and Bank",
		CashflowGroup:    "Operating",
		CashflowSubGroup: "Cash",
		IsTax:            false,
	},
	{
		Name:             "Kas Besar",
		Code:             "11002",
		Type:             ASSET,
		Category:         "Cash and Bank",
		CashflowGroup:    "Operating",
		CashflowSubGroup: "Cash",
		IsTax:            false,
	},
	{
		Name:             "Piutang Dagang",
		Code:             "12001",
		Type:             ASSET,
		Category:         "Receivables",
		CashflowGroup:    "Operating",
		CashflowSubGroup: "Accounts Receivable",
		IsTax:            false,
	},
	{
		Name:             "Piutang Bukan Dagang",
		Code:             "12002",
		Type:             ASSET,
		Category:         "Receivables",
		CashflowGroup:    "Operating",
		CashflowSubGroup: "Accounts Receivable",
		IsTax:            false,
	},
	{
		Name:             "Persediaan",
		Code:             "13001",
		Type:             ASSET,
		Category:         "Inventory",
		CashflowGroup:    "Operating",
		CashflowSubGroup: "Inventory",
		IsTax:            false,
	},
	{
		Name:             "Pendapatan",
		Code:             "41001",
		Type:             REVENUE,
		Category:         "Revenue",
		CashflowGroup:    "Operating",
		CashflowSubGroup: "Revenue",
		IsTax:            false,
	},
	{
		Name:             "Biaya Operasional",
		Code:             "51001",
		Type:             EXPENSE,
		Category:         "Operating Expenses",
		CashflowGroup:    "Operating",
		CashflowSubGroup: "Operating Expenses",
		IsTax:            false,
	},
	{
		Name:             "Biaya Bunga",
		Code:             "51002",
		Type:             EXPENSE,
		Category:         "Interest Expenses",
		CashflowGroup:    "Operating",
		CashflowSubGroup: "Interest Expenses",
		IsTax:            false,
	},
	{
		Name:             "Biaya Depresiasi",
		Code:             "51003",
		Type:             EXPENSE,
		Category:         "Depreciation Expenses",
		CashflowGroup:    "Operating",
		CashflowSubGroup: "Depreciation Expenses",
		IsTax:            false,
	},
	{
		Name:             "Biaya Pajak",
		Code:             "51004",
		Type:             EXPENSE,
		Category:         "Tax Expenses",
		CashflowGroup:    "Operating",
		CashflowSubGroup: "Tax Expenses",
		IsTax:            true,
	},
	{
		Name:             "Biaya Lain-Lain",
		Code:             "51005",
		Type:             EXPENSE,
		Category:         "Other Expenses",
		CashflowGroup:    "Operating",
		CashflowSubGroup: "Other Expenses",
		IsTax:            false,
	},
	{
		Name:             "Utang Dagang",
		Code:             "21001",
		Type:             LIABILITY,
		Category:         "Payables",
		CashflowGroup:    "Operating",
		CashflowSubGroup: "Accounts Payable",
		IsTax:            false,
	},
	{
		Name:             "Utang Bukan Dagang",
		Code:             "21002",
		Type:             LIABILITY,
		Category:         "Payables",
		CashflowGroup:    "Operating",
		CashflowSubGroup: "Accounts Payable",
		IsTax:            false,
	},
	{
		Name:             "Modal",
		Code:             "31001",
		Type:             EQUITY,
		Category:         "Equity",
		CashflowGroup:    "Investing",
		CashflowSubGroup: "Equity",
		IsTax:            false,
	},
	{
		Name:             "Pajak Masukan",
		Code:             "22001",
		Type:             LIABILITY,
		Category:         "Tax",
		CashflowGroup:    "Operating",
		CashflowSubGroup: "Tax",
		IsTax:            true,
	},
	{
		Name:             "Pajak Keluaran",
		Code:             "22002",
		Type:             LIABILITY,
		Category:         "Tax",
		CashflowGroup:    "Operating",
		CashflowSubGroup: "Tax",
		IsTax:            true,
	},
	{
		Name:             "Pinjaman Bank",
		Code:             "22003",
		Type:             LIABILITY,
		Category:         "Loan",
		CashflowGroup:    "Financing",
		CashflowSubGroup: "Loan",
		IsTax:            false,
	},
	{
		Name:             "Pinjaman Modal Non Bank",
		Code:             "22004",
		Type:             LIABILITY,
		Category:         "Loan",
		CashflowGroup:    "Financing",
		CashflowSubGroup: "Loan",
		IsTax:            false,
	},
}
