package account

import (
	"github.com/AMETORY/ametory-erp-modules/shared/constants"
	"github.com/AMETORY/ametory-erp-modules/shared/models"
)

var GenericChartOfAccount = []models.AccountModel{
	{
		Name:             "Kas Kecil",
		Code:             "11001",
		Type:             models.ASSET,
		Category:         "Cash and Bank",
		CashflowGroup:    "Operating",
		CashflowSubGroup: "Cash",
		IsTax:            false,
	},
	{
		Name:             "Kas Besar",
		Code:             "11002",
		Type:             models.ASSET,
		Category:         "Cash and Bank",
		CashflowGroup:    "Operating",
		CashflowSubGroup: "Cash",
		IsTax:            false,
	},
	{
		Name:             "BANK",
		Code:             "110023",
		Type:             models.ASSET,
		Category:         "Cash and Bank",
		CashflowGroup:    "Operating",
		CashflowSubGroup: "Cash",
		IsTax:            false,
	},
	{
		Name:             "Piutang Dagang",
		Code:             "12001",
		Type:             models.ASSET,
		Category:         "Receivables",
		CashflowGroup:    "Operating",
		CashflowSubGroup: "Accounts Receivable",
		IsTax:            false,
	},
	{
		Name:             "Piutang Bukan Dagang",
		Code:             "12002",
		Type:             models.ASSET,
		Category:         "Receivables",
		CashflowGroup:    "Operating",
		CashflowSubGroup: "Accounts Receivable",
		IsTax:            false,
	},
	{
		Name:             "Persediaan",
		Code:             "13001",
		Type:             models.ASSET,
		Category:         "Inventory",
		CashflowGroup:    "Operating",
		CashflowSubGroup: "Inventory",
		IsTax:            false,
	},
	{
		Name:             "Pendapatan",
		Code:             "41001",
		Type:             models.REVENUE,
		Category:         "Revenue",
		CashflowGroup:    "Operating",
		CashflowSubGroup: "Revenue",
		IsTax:            false,
	},
	{
		Name:             "Biaya Operasional",
		Code:             "51001",
		Type:             models.EXPENSE,
		Category:         "Operating Expenses",
		CashflowGroup:    "Operating",
		CashflowSubGroup: "Operating Expenses",
		IsTax:            false,
	},
	{
		Name:             "Biaya Bunga",
		Code:             "51002",
		Type:             models.EXPENSE,
		Category:         "Interest Expenses",
		CashflowGroup:    "Operating",
		CashflowSubGroup: "Interest Expenses",
		IsTax:            false,
	},
	{
		Name:             "Biaya Depresiasi",
		Code:             "51003",
		Type:             models.EXPENSE,
		Category:         "Depreciation Expenses",
		CashflowGroup:    "Operating",
		CashflowSubGroup: "Depreciation Expenses",
		IsTax:            false,
	},
	{
		Name:             "Biaya Pajak",
		Code:             "51004",
		Type:             models.EXPENSE,
		Category:         "Tax Expenses",
		CashflowGroup:    "Operating",
		CashflowSubGroup: "Tax Expenses",
		IsTax:            true,
	},
	{
		Name:             "Biaya Lain-Lain",
		Code:             "51005",
		Type:             models.EXPENSE,
		Category:         "Other Expenses",
		CashflowGroup:    "Operating",
		CashflowSubGroup: "Other Expenses",
		IsTax:            false,
	},
	{
		Name:             "Utang Dagang",
		Code:             "21001",
		Type:             models.LIABILITY,
		Category:         "Payables",
		CashflowGroup:    "Operating",
		CashflowSubGroup: "Accounts Payable",
		IsTax:            false,
	},
	{
		Name:             "Utang Bukan Dagang",
		Code:             "21002",
		Type:             models.LIABILITY,
		Category:         "Payables",
		CashflowGroup:    "Operating",
		CashflowSubGroup: "Accounts Payable",
		IsTax:            false,
	},
	{
		Name:             "Modal",
		Code:             "31001",
		Type:             models.EQUITY,
		Category:         "Equity",
		CashflowGroup:    "Investing",
		CashflowSubGroup: "Equity",
		IsTax:            false,
	},
	{
		Name:             "Pajak Masukan",
		Code:             "22001",
		Type:             models.LIABILITY,
		Category:         "Tax",
		CashflowGroup:    "Operating",
		CashflowSubGroup: "Tax",
		IsTax:            true,
	},
	{
		Name:             "Pajak Keluaran",
		Code:             "22002",
		Type:             models.LIABILITY,
		Category:         "Tax",
		CashflowGroup:    "Operating",
		CashflowSubGroup: "Tax",
		IsTax:            true,
	},
	{
		Name:             "Pinjaman Bank",
		Code:             "22003",
		Type:             models.LIABILITY,
		Category:         "Loan",
		CashflowGroup:    "Financing",
		CashflowSubGroup: "Loan",
		IsTax:            false,
	},
	{
		Name:             "Pinjaman Modal Non Bank",
		Code:             "22004",
		Type:             models.LIABILITY,
		Category:         "Loan",
		CashflowGroup:    "Financing",
		CashflowSubGroup: "Loan",
		IsTax:            false,
	},
}
var CooperationAccountsTemplate = []models.AccountModel{
	{
		CashflowSubGroup: constants.CASH_BANK,
		CashflowGroup:    constants.CASHFLOW_GROUP_CURRENT_ASSET,
		Category:         constants.CATEGORY_CURRENT_ASSET,
		Name:             "Kas",
		Type:             models.ASSET,
		Code:             "11001",
	},
	{
		CashflowSubGroup: constants.CASH_BANK,
		CashflowGroup:    constants.CASHFLOW_GROUP_CURRENT_ASSET,
		Category:         constants.CATEGORY_CURRENT_ASSET,
		Name:             "Bank",
		Type:             models.ASSET,
		Code:             "11002",
	},
	{
		CashflowSubGroup: constants.ACCEPTANCE_FROM_CUSTOMERS,
		CashflowGroup:    constants.CASHFLOW_GROUP_OPERATING,
		Category:         constants.CATEGORY_RECEIVABLE,
		Name:             "Piutang Pinjaman",
		Type:             models.RECEIVABLE,
		Code:             "11003",
	},
	{
		CashflowSubGroup: constants.ACCEPTANCE_FROM_CUSTOMERS,
		CashflowGroup:    constants.CASHFLOW_GROUP_OPERATING,
		Category:         constants.CATEGORY_RECEIVABLE,
		Name:             "Piutang Bunga",
		Type:             models.RECEIVABLE,
		Code:             "11004",
	},
	{
		CashflowSubGroup: constants.ACCEPTANCE_FROM_CUSTOMERS,
		CashflowGroup:    constants.CASHFLOW_GROUP_OPERATING,
		Category:         constants.CATEGORY_RECEIVABLE,
		Name:             "Piutang Lain-lain",
		Type:             models.RECEIVABLE,
		Code:             "11005",
	},
	{
		CashflowSubGroup: constants.CASHFLOW_GROUP_FIXED_ASSET,
		CashflowGroup:    constants.CASHFLOW_GROUP_FIXED_ASSET,
		Category:         constants.CATEGORY_FIXED_ASSET,
		Name:             "Aset Tetap",
		Type:             models.ASSET,
		Code:             "11007",
	},
	{
		CashflowSubGroup: constants.CASHFLOW_GROUP_DEPRECIATION_AMORTIZATION,
		CashflowGroup:    constants.CASHFLOW_GROUP_FIXED_ASSET,
		Category:         constants.CATEGORY_FIXED_ASSET,
		Name:             "Akumulasi Penyusutan",
		Type:             models.ASSET,
		Code:             "11008",
	},
	{
		CashflowSubGroup: constants.CASHFLOW_GROUP_FIXED_ASSET,
		CashflowGroup:    constants.CASHFLOW_GROUP_FIXED_ASSET,
		Category:         constants.CATEGORY_FIXED_ASSET,
		Name:             "Investasi Jangka Panjang",
		Type:             models.ASSET,
		Code:             "11009",
	},
	{
		CashflowSubGroup: constants.PAYMENT_TO_VENDORS,
		CashflowGroup:    constants.CASHFLOW_GROUP_OPERATING,
		Category:         constants.CATEGORY_DEBT,
		Name:             "Hutang Bunga Simpanan",
		Type:             models.LIABILITY,
		Code:             "21001",
	},
	{
		CashflowSubGroup: constants.PAYMENT_TO_VENDORS,
		CashflowGroup:    constants.CASHFLOW_GROUP_OPERATING,
		Category:         constants.CATEGORY_DEBT,
		Name:             "Hutang Jangka Pendek",
		Type:             models.LIABILITY,
		Code:             "21002",
	},
	{
		CashflowSubGroup: constants.PAYMENT_TO_VENDORS,
		CashflowGroup:    constants.CASHFLOW_GROUP_OPERATING,
		Category:         constants.CATEGORY_DEBT,
		Name:             "Hutang Operasional",
		Type:             models.LIABILITY,
		Code:             "21003",
	},
	{
		CashflowSubGroup: constants.PAYMENT_TO_VENDORS,
		CashflowGroup:    constants.CASHFLOW_GROUP_OPERATING,
		Category:         constants.CATEGORY_DEBT,
		Name:             "Hutang Jangka Panjang",
		Type:             models.LIABILITY,
		Code:             "21004",
	},
	{
		CashflowSubGroup: constants.EQUITY_CAPITAL,
		CashflowGroup:    constants.CASHFLOW_GROUP_FINANCING,
		Category:         constants.CATEGORY_EQUITY,
		Name:             "Simpanan Pokok",
		Type:             models.EQUITY,
		Code:             "31001",
	},
	{
		CashflowSubGroup: constants.EQUITY_CAPITAL,
		CashflowGroup:    constants.CASHFLOW_GROUP_FINANCING,
		Category:         constants.CATEGORY_EQUITY,
		Name:             "Simpanan Wajib",
		Type:             models.EQUITY,
		Code:             "31002",
	},
	{
		CashflowSubGroup: constants.EQUITY_CAPITAL,
		CashflowGroup:    constants.CASHFLOW_GROUP_FINANCING,
		Category:         constants.CATEGORY_EQUITY,
		Name:             "Simpanan Sukarela",
		Type:             models.EQUITY,
		Code:             "31003",
	},

	{
		CashflowSubGroup: constants.EQUITY_CAPITAL,
		CashflowGroup:    constants.CASHFLOW_GROUP_FINANCING,
		Category:         constants.CATEGORY_EQUITY,
		Name:             "Sisa Hasil Usaha (SHU) yang Belum Dibagi",
		Type:             models.EQUITY,
		Code:             "31005",
	},
	{
		CashflowSubGroup: constants.ACCEPTANCE_FROM_CUSTOMERS,
		CashflowGroup:    constants.CASHFLOW_GROUP_OPERATING,
		Category:         constants.CATEGORY_SALES,
		Name:             "Pendapatan Bunga Pinjaman",
		Type:             models.INCOME,
		Code:             "41001",
	},
	{
		CashflowSubGroup: constants.ACCEPTANCE_FROM_CUSTOMERS,
		CashflowGroup:    constants.CASHFLOW_GROUP_OPERATING,
		Category:         constants.CATEGORY_SALES,
		Name:             "Pendapatan Administrasi",
		Type:             models.INCOME,
		Code:             "41002",
	},
	{
		CashflowSubGroup: constants.ACCEPTANCE_FROM_CUSTOMERS,
		CashflowGroup:    constants.CASHFLOW_GROUP_OPERATING,
		Category:         constants.CATEGORY_SALES,
		Name:             "Pendapatan Jasa Lainnya",
		Type:             models.INCOME,
		Code:             "41003",
	},
	{
		CashflowSubGroup: constants.ACCEPTANCE_FROM_CUSTOMERS,
		CashflowGroup:    constants.CASHFLOW_GROUP_OPERATING,
		Category:         constants.CATEGORY_SALES,
		Name:             "Pendapatan Investasi",
		Type:             models.INCOME,
		Code:             "41004",
	},
	{
		CashflowSubGroup: constants.ACCEPTANCE_FROM_CUSTOMERS,
		CashflowGroup:    constants.CASHFLOW_GROUP_OPERATING,
		Category:         constants.CATEGORY_SALES,
		Name:             "Pendapatan Penjualan Barang - Anggota",
		Type:             models.INCOME,
		Code:             "41005",
	},
	{
		CashflowSubGroup: constants.ACCEPTANCE_FROM_CUSTOMERS,
		CashflowGroup:    constants.CASHFLOW_GROUP_OPERATING,
		Category:         constants.CATEGORY_SALES,
		Name:             "Pendapatan Penjualan Barang - Non-Anggota",
		Type:             models.INCOME,
		Code:             "41006",
	},
	{
		CashflowSubGroup: constants.ACCEPTANCE_FROM_CUSTOMERS,
		CashflowGroup:    constants.CASHFLOW_GROUP_OPERATING,
		Category:         constants.CATEGORY_OTHER_INCOME,
		Name:             "Pendapatan Biaya Admin",
		Type:             models.INCOME,
		Code:             "41011",
	},
	{
		CashflowSubGroup: constants.OPERATIONAL_EXPENSES,
		CashflowGroup:    constants.CASHFLOW_GROUP_OPERATING,
		Category:         constants.CATEGORY_EXPENSE,
		Name:             "Beban Bunga Simpanan",
		Type:             models.EXPENSE,
		Code:             "51001",
	},
	{
		CashflowSubGroup: constants.OPERATIONAL_EXPENSES,
		CashflowGroup:    constants.CASHFLOW_GROUP_OPERATING,
		Category:         constants.CATEGORY_EXPENSE,
		Name:             "Beban Administrasi",
		Type:             models.EXPENSE,
		Code:             "51002",
	},
	{
		CashflowSubGroup: constants.OPERATIONAL_EXPENSES,
		CashflowGroup:    constants.CASHFLOW_GROUP_OPERATING,
		Category:         constants.CATEGORY_EXPENSE,
		Name:             "Beban Gaji dan Tunjangan",
		Type:             models.EXPENSE,
		Code:             "51003",
	},
	{
		CashflowSubGroup: constants.ACQUISITION_SALE_OF_ASSETS,
		CashflowGroup:    constants.CASHFLOW_GROUP_INVESTING,
		Category:         constants.CATEGORY_EXPENSE,
		Name:             "Beban Penyusutan",
		Type:             models.EXPENSE,
		Code:             "51004",
	},
	{
		CashflowSubGroup: constants.OPERATIONAL_EXPENSES,
		CashflowGroup:    constants.CASHFLOW_GROUP_OPERATING,
		Category:         constants.CATEGORY_COST_OF_REVENUE,
		Name:             "Beban Operasional Lainnya",
		Type:             models.COST,
		Code:             "61001",
	},
	{
		CashflowSubGroup: constants.OPERATIONAL_EXPENSES,
		CashflowGroup:    constants.CASHFLOW_GROUP_OPERATING,
		Category:         constants.CATEGORY_COST_OF_REVENUE,
		Name:             "Beban Operasional Penjualan",
		Type:             models.COST,
		Code:             "61002",
	},
}
var IslamicCooperationAccountsTemplate = []models.AccountModel{
	// Aset
	{
		CashflowSubGroup: constants.CASH_BANK,
		CashflowGroup:    constants.CASHFLOW_GROUP_CURRENT_ASSET,
		Category:         constants.CATEGORY_CURRENT_ASSET,
		Name:             "Kas",
		Type:             models.ASSET,
		Code:             "11001",
	},
	{
		CashflowSubGroup: constants.CASH_BANK,
		CashflowGroup:    constants.CASHFLOW_GROUP_CURRENT_ASSET,
		Category:         constants.CATEGORY_CURRENT_ASSET,
		Name:             "Bank",
		Type:             models.ASSET,
		Code:             "11002",
	},
	// {
	// 	CashflowSubGroup: constants.INVESTMENT_PARTNERSHIP,
	// 	CashflowGroup:    constants.CASHFLOW_GROUP_INVESTING,
	// 	Category:         constants.CATEGORY_CURRENT_ASSET,
	// 	Name:             "Investasi Mudharabah",
	// 	Type:             models.ASSET,
	// 	Code:             "11003",
	// },
	{
		CashflowSubGroup: constants.CASHFLOW_GROUP_FIXED_ASSET,
		CashflowGroup:    constants.CASHFLOW_GROUP_FIXED_ASSET,
		Category:         constants.CATEGORY_FIXED_ASSET,
		Name:             "Aset Tanah",
		Type:             models.ASSET,
		Code:             "11005",
	},
	{
		CashflowSubGroup: constants.CASHFLOW_GROUP_FIXED_ASSET,
		CashflowGroup:    constants.CASHFLOW_GROUP_FIXED_ASSET,
		Category:         constants.CATEGORY_FIXED_ASSET,
		Name:             "Aset Bangunan",
		Type:             models.ASSET,
		Code:             "11006",
	},
	{
		CashflowSubGroup: constants.CASHFLOW_GROUP_FIXED_ASSET,
		CashflowGroup:    constants.CASHFLOW_GROUP_FIXED_ASSET,
		Category:         constants.CATEGORY_FIXED_ASSET,
		Name:             "Aset Kendaraan",
		Type:             models.ASSET,
		Code:             "11007",
	},
	{
		CashflowSubGroup: constants.CASHFLOW_GROUP_FIXED_ASSET,
		CashflowGroup:    constants.CASHFLOW_GROUP_FIXED_ASSET,
		Category:         constants.CATEGORY_FIXED_ASSET,
		Name:             "Aset Peralatan Kantor",
		Type:             models.ASSET,
		Code:             "11008",
	},
	// Piutang
	{
		CashflowSubGroup: constants.INVESTMENT_PARTNERSHIP,
		CashflowGroup:    constants.CASHFLOW_GROUP_INVESTING,
		Category:         constants.CATEGORY_RECEIVABLE,
		Name:             "Piutang Qardh Hasan",
		Type:             models.RECEIVABLE,
		Code:             "12001",
	},
	{
		CashflowSubGroup: constants.INVESTMENT_PARTNERSHIP,
		CashflowGroup:    constants.CASHFLOW_GROUP_INVESTING,
		Category:         constants.CATEGORY_RECEIVABLE,
		Name:             "Piutang Murabahah",
		Type:             models.RECEIVABLE,
		Code:             "12002",
	},
	{
		CashflowSubGroup: constants.INVESTMENT_PARTNERSHIP,
		CashflowGroup:    constants.CASHFLOW_GROUP_INVESTING,
		Category:         constants.CATEGORY_RECEIVABLE,
		Name:             "Piutang Mudharabah",
		Type:             models.RECEIVABLE,
		Code:             "12004",
	},
	{
		CashflowSubGroup: constants.ACCEPTANCE_FROM_CUSTOMERS,
		CashflowGroup:    constants.CASHFLOW_GROUP_OPERATING,
		Category:         constants.CATEGORY_RECEIVABLE,
		Name:             "Piutang Lainnya",
		Type:             models.RECEIVABLE,
		Code:             "12003",
	},

	// Kewajiban
	{
		CashflowSubGroup: constants.PAYMENT_TO_VENDORS,
		CashflowGroup:    constants.CASHFLOW_GROUP_FINANCING,
		Category:         constants.CATEGORY_DEBT,
		Name:             "Hutang Bank Syariah",
		Type:             models.LIABILITY,
		Code:             "21001",
	},
	{
		CashflowSubGroup: constants.PAYMENT_TO_VENDORS,
		CashflowGroup:    constants.CASHFLOW_GROUP_FINANCING,
		Category:         constants.CATEGORY_DEBT,
		Name:             "Hutang Usaha",
		Type:             models.LIABILITY,
		Code:             "21002",
	},
	{
		CashflowSubGroup: constants.CREDIT_CARDS_AND_OTHER_SHORT_TERM_LIABILITIES,
		CashflowGroup:    constants.CASHFLOW_GROUP_FINANCING,
		Category:         constants.CATEGORY_DEBT,
		Name:             "Titipan Zakat Infaq Sadaqah",
		Type:             models.LIABILITY,
		Code:             "21003",
	},
	{
		CashflowSubGroup: constants.CREDIT_CARDS_AND_OTHER_SHORT_TERM_LIABILITIES,
		CashflowGroup:    constants.CASHFLOW_GROUP_FINANCING,
		Category:         constants.CATEGORY_DEBT,
		Name:             "Dana Amanah",
		Type:             models.LIABILITY,
		Code:             "21004",
	},
	{
		CashflowSubGroup: constants.CREDIT_CARDS_AND_OTHER_SHORT_TERM_LIABILITIES,
		CashflowGroup:    constants.CASHFLOW_GROUP_FINANCING,
		Category:         constants.CATEGORY_DEBT,
		Name:             "Hutang Lainnya",
		Type:             models.LIABILITY,
		Code:             "21005",
	},
	{
		CashflowSubGroup: constants.LOAN_PAYMENTS_RECEIPTS,
		CashflowGroup:    constants.CASHFLOW_GROUP_FINANCING,
		Category:         constants.CATEGORY_DEBT,
		Name:             "Pinjaman Bank",
		Type:             models.LIABILITY,
		Code:             "21006",
	},
	// Modal
	{
		CashflowSubGroup: constants.EQUITY_CAPITAL,
		CashflowGroup:    constants.CASHFLOW_GROUP_FINANCING,
		Category:         constants.CATEGORY_EQUITY,
		Name:             "Modal Penyertaan",
		Type:             models.EQUITY,
		Code:             "31001",
	},
	{
		CashflowSubGroup: constants.EQUITY_CAPITAL,
		CashflowGroup:    constants.CASHFLOW_GROUP_FINANCING,
		Category:         constants.CATEGORY_EQUITY,
		Name:             "Simpanan Pokok",
		Type:             models.EQUITY,
		Code:             "31005",
	},
	{
		CashflowSubGroup: constants.EQUITY_CAPITAL,
		CashflowGroup:    constants.CASHFLOW_GROUP_FINANCING,
		Category:         constants.CATEGORY_EQUITY,
		Name:             "Simpanan Wajib",
		Type:             models.EQUITY,
		Code:             "31006",
	},
	{
		CashflowSubGroup: constants.EQUITY_CAPITAL,
		CashflowGroup:    constants.CASHFLOW_GROUP_FINANCING,
		Category:         constants.CATEGORY_EQUITY,
		Name:             "Simpanan Sukarela",
		Type:             models.EQUITY,
		Code:             "31007",
	},
	// Pendapatan
	{
		CashflowSubGroup: constants.ACCEPTANCE_FROM_CUSTOMERS,
		CashflowGroup:    constants.CASHFLOW_GROUP_OPERATING,
		Category:         constants.CATEGORY_OTHER_INCOME,
		Name:             "Pendapatan Mudharabah",
		Type:             models.INCOME,
		Code:             "41001",
	},
	{
		CashflowSubGroup: constants.ACCEPTANCE_FROM_CUSTOMERS,
		CashflowGroup:    constants.CASHFLOW_GROUP_OPERATING,
		Category:         constants.CATEGORY_OTHER_INCOME,
		Name:             "Pendapatan Murabahah",
		Type:             models.INCOME,
		Code:             "41002",
	},
	{
		CashflowSubGroup: constants.ACCEPTANCE_FROM_CUSTOMERS,
		CashflowGroup:    constants.CASHFLOW_GROUP_OPERATING,
		Category:         constants.CATEGORY_OTHER_INCOME,
		Name:             "Pendapatan Administrasi",
		Type:             models.INCOME,
		Code:             "41003",
	},
	{
		CashflowSubGroup: constants.ACCEPTANCE_FROM_CUSTOMERS,
		CashflowGroup:    constants.CASHFLOW_GROUP_OPERATING,
		Category:         constants.CATEGORY_OTHER_INCOME,
		Name:             "Pendapatan Qardh Hasan",
		Type:             models.INCOME,
		Code:             "41004",
	},
	{
		CashflowSubGroup: constants.ACCEPTANCE_FROM_CUSTOMERS,
		CashflowGroup:    constants.CASHFLOW_GROUP_OPERATING,
		Category:         constants.CATEGORY_OTHER_INCOME,
		Name:             "Pendapatan Lainnya",
		Type:             models.INCOME,
		Code:             "41005",
	},
	{
		CashflowSubGroup: constants.ACCEPTANCE_FROM_CUSTOMERS,
		CashflowGroup:    constants.CASHFLOW_GROUP_OPERATING,
		Category:         constants.CATEGORY_OTHER_INCOME,
		Name:             "Pendapatan Zakat",
		Type:             models.INCOME,
		Code:             "41006",
	},
	{
		CashflowSubGroup: constants.ACCEPTANCE_FROM_CUSTOMERS,
		CashflowGroup:    constants.CASHFLOW_GROUP_OPERATING,
		Category:         constants.CATEGORY_OTHER_INCOME,
		Name:             "Pendapatan Infaq",
		Type:             models.INCOME,
		Code:             "41007",
	},
	{
		CashflowSubGroup: constants.ACCEPTANCE_FROM_CUSTOMERS,
		CashflowGroup:    constants.CASHFLOW_GROUP_OPERATING,
		Category:         constants.CATEGORY_OTHER_INCOME,
		Name:             "Pendapatan Sadaqah",
		Type:             models.INCOME,
		Code:             "41008",
	},
	{
		CashflowSubGroup: constants.ACCEPTANCE_FROM_CUSTOMERS,
		CashflowGroup:    constants.CASHFLOW_GROUP_OPERATING,
		Category:         constants.CATEGORY_OTHER_INCOME,
		Name:             "Penerimaan Dana ZIS",
		Type:             models.INCOME,
		Code:             "41009",
	},
	{
		CashflowSubGroup: constants.ACCEPTANCE_FROM_CUSTOMERS,
		CashflowGroup:    constants.CASHFLOW_GROUP_OPERATING,
		Category:         constants.CATEGORY_OTHER_INCOME,
		Name:             "Penyaluran Dana ZIS",
		Type:             models.INCOME,
		Code:             "41010",
	},
	{
		CashflowSubGroup: constants.ACCEPTANCE_FROM_CUSTOMERS,
		CashflowGroup:    constants.CASHFLOW_GROUP_OPERATING,
		Category:         constants.CATEGORY_OTHER_INCOME,
		Name:             "Pendapatan Biaya Admin",
		Type:             models.INCOME,
		Code:             "41011",
	},
	// Pengeluaran
	{
		CashflowSubGroup: constants.OPERATIONAL_EXPENSES,
		CashflowGroup:    constants.CASHFLOW_GROUP_OPERATING,
		Category:         constants.CATEGORY_EXPENSE,
		Name:             "Beban Administrasi",
		Type:             models.EXPENSE,
		Code:             "51001",
	},
	{
		CashflowSubGroup: constants.OPERATIONAL_EXPENSES,
		CashflowGroup:    constants.CASHFLOW_GROUP_OPERATING,
		Category:         constants.CATEGORY_EXPENSE,
		Name:             "Beban Utilitas",
		Type:             models.EXPENSE,
		Code:             "51002",
	},

	{
		CashflowSubGroup: constants.OPERATIONAL_EXPENSES,
		CashflowGroup:    constants.CASHFLOW_GROUP_OPERATING,
		Category:         constants.CATEGORY_EXPENSE,
		Name:             "Beban Transportasi",
		Type:             models.EXPENSE,
		Code:             "51003",
	},
	{
		CashflowSubGroup: constants.OPERATIONAL_EXPENSES,
		CashflowGroup:    constants.CASHFLOW_GROUP_OPERATING,
		Category:         constants.CATEGORY_EXPENSE,
		Name:             "Beban Bagi Hasil Mudharabah",
		Type:             models.EXPENSE,
		Code:             "51004",
	},
	{
		CashflowSubGroup: constants.OPERATIONAL_EXPENSES,
		CashflowGroup:    constants.CASHFLOW_GROUP_OPERATING,
		Category:         constants.CATEGORY_EXPENSE,
		Name:             "Beban Penyusutan",
		Type:             models.EXPENSE,
		Code:             "51005",
	},
	{
		CashflowSubGroup: constants.OPERATIONAL_EXPENSES,
		CashflowGroup:    constants.CASHFLOW_GROUP_OPERATING,
		Category:         constants.CATEGORY_EXPENSE,
		Name:             "Beban Lainnya",
		Type:             models.EXPENSE,
		Code:             "51006",
	},
	{
		CashflowSubGroup: constants.OPERATIONAL_EXPENSES,
		CashflowGroup:    constants.CASHFLOW_GROUP_OPERATING,
		Category:         constants.CATEGORY_EXPENSE,
		Name:             "Beban Penyaluran Zakat",
		Type:             models.EXPENSE,
		Code:             "51007",
	},
	{
		CashflowSubGroup: constants.OPERATIONAL_EXPENSES,
		CashflowGroup:    constants.CASHFLOW_GROUP_OPERATING,
		Category:         constants.CATEGORY_EXPENSE,
		Name:             "Beban Penyaluran Infaq",
		Type:             models.EXPENSE,
		Code:             "51008",
	},
	{
		CashflowSubGroup: constants.OPERATIONAL_EXPENSES,
		CashflowGroup:    constants.CASHFLOW_GROUP_OPERATING,
		Category:         constants.CATEGORY_EXPENSE,
		Name:             "Beban Penyaluran Sadaqah",
		Type:             models.EXPENSE,
		Code:             "51009",
	},
}
