package cooperative

import (
	"github.com/AMETORY/ametory-erp-modules/company"
	"github.com/AMETORY/ametory-erp-modules/context"
	"github.com/AMETORY/ametory-erp-modules/cooperative/cooperative_member"
	"github.com/AMETORY/ametory-erp-modules/cooperative/cooperative_setting"
	"github.com/AMETORY/ametory-erp-modules/cooperative/loan_application"
	"github.com/AMETORY/ametory-erp-modules/cooperative/net_surplus"
	"github.com/AMETORY/ametory-erp-modules/cooperative/saving"
	"github.com/AMETORY/ametory-erp-modules/finance"
	"github.com/AMETORY/ametory-erp-modules/shared/constants"
	"github.com/AMETORY/ametory-erp-modules/shared/models"
)

type CooperativeService struct {
	ctx                       *context.ERPContext
	companyService            *company.CompanyService
	cooperativeSettingService *cooperative_setting.CooperativeSettingService
	cooperativeMemberService  *cooperative_member.CooperativeMemberService
	loanApplicationService    *loan_application.LoanApplicationService
	savingService             *saving.SavingService
	netSurplusService         *net_surplus.NetSurplusService
	financeService            *finance.FinanceService
}

func NewCooperativeService(ctx *context.ERPContext, companySrv *company.CompanyService, financeService *finance.FinanceService) *CooperativeService {
	cooperativeSettingService := cooperative_setting.NewCooperativeSettingService(ctx.DB, ctx)
	savingService := saving.NewSavingService(ctx.DB, ctx, cooperativeSettingService)
	var service = CooperativeService{
		ctx:                       ctx,
		companyService:            companySrv,
		cooperativeSettingService: cooperativeSettingService,
		cooperativeMemberService:  cooperative_member.NewCooperativeMemberService(ctx.DB, ctx),
		savingService:             savingService,
		loanApplicationService:    loan_application.NewLoanApplicationService(ctx.DB, ctx, cooperativeSettingService, savingService),
		netSurplusService:         net_surplus.NewNetSurplusService(ctx.DB, ctx, cooperativeSettingService, financeService),
		financeService:            financeService,
	}
	if err := service.Migrate(); err != nil {
		panic(err)
	}
	return &service
}

func (s *CooperativeService) Migrate() error {
	if s.ctx.SkipMigration {
		return nil
	}
	return s.ctx.DB.AutoMigrate(
		&models.CooperativeSettingModel{},
		&models.CooperativeMemberModel{},
		&models.LoanApplicationModel{},
		&models.SavingModel{},
		&models.InstallmentPayment{},
		&models.NetSurplusModel{},
	)
}

func (c *CooperativeService) IslamicCooperationAccountsTemplate(userID, companyID *string) []models.AccountModel {
	accounts := []models.AccountModel{
		// Aset
		{
			CashflowSubGroup: constants.CASH_BANK,
			CashflowGroup:    constants.CASHFLOW_GROUP_CURRENT_ASSET,
			Category:         constants.CATEGORY_CURRENT_ASSET,
			Name:             "Kas",
			Type:             models.ASSET,
			UserID:           userID,
			CompanyID:        companyID,
			Code:             "11001",
		},
		{
			CashflowSubGroup: constants.CASH_BANK,
			CashflowGroup:    constants.CASHFLOW_GROUP_CURRENT_ASSET,
			Category:         constants.CATEGORY_CURRENT_ASSET,
			Name:             "Bank",
			Type:             models.ASSET,
			UserID:           userID,
			CompanyID:        companyID,
			Code:             "11002",
		},
		// {
		// 	CashflowSubGroup: constants.INVESTMENT_PARTNERSHIP,
		// 	CashflowGroup:    constants.CASHFLOW_GROUP_INVESTING,
		// 	Category:         constants.CATEGORY_CURRENT_ASSET,
		// 	Name:             "Investasi Mudharabah",
		// 	Type:             models.ASSET,
		// 	UserID:           userID,
		// 	CompanyID:        companyID,
		// 	Code:             "11003",
		// },
		{
			CashflowSubGroup: constants.CASHFLOW_GROUP_FIXED_ASSET,
			CashflowGroup:    constants.CASHFLOW_GROUP_FIXED_ASSET,
			Category:         constants.CATEGORY_FIXED_ASSET,
			Name:             "Aset Tanah",
			Type:             models.ASSET,
			UserID:           userID,
			CompanyID:        companyID,
			Code:             "11005",
		},
		{
			CashflowSubGroup: constants.CASHFLOW_GROUP_FIXED_ASSET,
			CashflowGroup:    constants.CASHFLOW_GROUP_FIXED_ASSET,
			Category:         constants.CATEGORY_FIXED_ASSET,
			Name:             "Aset Bangunan",
			Type:             models.ASSET,
			UserID:           userID,
			CompanyID:        companyID,
			Code:             "11006",
		},
		{
			CashflowSubGroup: constants.CASHFLOW_GROUP_FIXED_ASSET,
			CashflowGroup:    constants.CASHFLOW_GROUP_FIXED_ASSET,
			Category:         constants.CATEGORY_FIXED_ASSET,
			Name:             "Aset Kendaraan",
			Type:             models.ASSET,
			UserID:           userID,
			CompanyID:        companyID,
			Code:             "11007",
		},
		{
			CashflowSubGroup: constants.CASHFLOW_GROUP_FIXED_ASSET,
			CashflowGroup:    constants.CASHFLOW_GROUP_FIXED_ASSET,
			Category:         constants.CATEGORY_FIXED_ASSET,
			Name:             "Aset Peralatan Kantor",
			Type:             models.ASSET,
			UserID:           userID,
			CompanyID:        companyID,
			Code:             "11008",
		},
		// Piutang
		{
			CashflowSubGroup: constants.INVESTMENT_PARTNERSHIP,
			CashflowGroup:    constants.CASHFLOW_GROUP_INVESTING,
			Category:         constants.CATEGORY_RECEIVABLE,
			Name:             "Piutang Qardh Hasan",
			Type:             models.RECEIVABLE,
			UserID:           userID,
			CompanyID:        companyID,
			Code:             "12001",
		},
		{
			CashflowSubGroup: constants.INVESTMENT_PARTNERSHIP,
			CashflowGroup:    constants.CASHFLOW_GROUP_INVESTING,
			Category:         constants.CATEGORY_RECEIVABLE,
			Name:             "Piutang Murabahah",
			Type:             models.RECEIVABLE,
			UserID:           userID,
			CompanyID:        companyID,
			Code:             "12002",
		},
		{
			CashflowSubGroup: constants.INVESTMENT_PARTNERSHIP,
			CashflowGroup:    constants.CASHFLOW_GROUP_INVESTING,
			Category:         constants.CATEGORY_RECEIVABLE,
			Name:             "Piutang Mudharabah",
			Type:             models.RECEIVABLE,
			UserID:           userID,
			CompanyID:        companyID,
			Code:             "12004",
		},
		{
			CashflowSubGroup: constants.ACCEPTANCE_FROM_CUSTOMERS,
			CashflowGroup:    constants.CASHFLOW_GROUP_OPERATING,
			Category:         constants.CATEGORY_RECEIVABLE,
			Name:             "Piutang Lainnya",
			Type:             models.RECEIVABLE,
			UserID:           userID,
			CompanyID:        companyID,
			Code:             "12003",
		},

		// Kewajiban
		{
			CashflowSubGroup: constants.PAYMENT_TO_VENDORS,
			CashflowGroup:    constants.CASHFLOW_GROUP_FINANCING,
			Category:         constants.CATEGORY_DEBT,
			Name:             "Hutang Bank Syariah",
			Type:             models.LIABILITY,
			UserID:           userID,
			CompanyID:        companyID,
			Code:             "21001",
		},
		{
			CashflowSubGroup: constants.PAYMENT_TO_VENDORS,
			CashflowGroup:    constants.CASHFLOW_GROUP_FINANCING,
			Category:         constants.CATEGORY_DEBT,
			Name:             "Hutang Usaha",
			Type:             models.LIABILITY,
			UserID:           userID,
			CompanyID:        companyID,
			Code:             "21002",
		},
		{
			CashflowSubGroup: constants.CREDIT_CARDS_AND_OTHER_SHORT_TERM_LIABILITIES,
			CashflowGroup:    constants.CASHFLOW_GROUP_FINANCING,
			Category:         constants.CATEGORY_DEBT,
			Name:             "Titipan Zakat Infaq Sadaqah",
			Type:             models.LIABILITY,
			UserID:           userID,
			CompanyID:        companyID,
			Code:             "21003",
		},
		{
			CashflowSubGroup: constants.CREDIT_CARDS_AND_OTHER_SHORT_TERM_LIABILITIES,
			CashflowGroup:    constants.CASHFLOW_GROUP_FINANCING,
			Category:         constants.CATEGORY_DEBT,
			Name:             "Dana Amanah",
			Type:             models.LIABILITY,
			UserID:           userID,
			CompanyID:        companyID,
			Code:             "21004",
		},
		{
			CashflowSubGroup: constants.CREDIT_CARDS_AND_OTHER_SHORT_TERM_LIABILITIES,
			CashflowGroup:    constants.CASHFLOW_GROUP_FINANCING,
			Category:         constants.CATEGORY_DEBT,
			Name:             "Hutang Lainnya",
			Type:             models.LIABILITY,
			UserID:           userID,
			CompanyID:        companyID,
			Code:             "21005",
		},
		{
			CashflowSubGroup: constants.LOAN_PAYMENTS_RECEIPTS,
			CashflowGroup:    constants.CASHFLOW_GROUP_FINANCING,
			Category:         constants.CATEGORY_DEBT,
			Name:             "Pinjaman Bank",
			Type:             models.LIABILITY,
			UserID:           userID,
			CompanyID:        companyID,
			Code:             "21006",
		},
		// Modal
		{
			CashflowSubGroup: constants.EQUITY_CAPITAL,
			CashflowGroup:    constants.CASHFLOW_GROUP_FINANCING,
			Category:         constants.CATEGORY_EQUITY,
			Name:             "Modal Penyertaan",
			Type:             models.EQUITY,
			UserID:           userID,
			CompanyID:        companyID,
			Code:             "31001",
		},
		{
			CashflowSubGroup: constants.EQUITY_CAPITAL,
			CashflowGroup:    constants.CASHFLOW_GROUP_FINANCING,
			Category:         constants.CATEGORY_EQUITY,
			Name:             "Simpanan Pokok",
			Type:             models.EQUITY,
			UserID:           userID,
			CompanyID:        companyID,
			Code:             "31005",
		},
		{
			CashflowSubGroup: constants.EQUITY_CAPITAL,
			CashflowGroup:    constants.CASHFLOW_GROUP_FINANCING,
			Category:         constants.CATEGORY_EQUITY,
			Name:             "Simpanan Wajib",
			Type:             models.EQUITY,
			UserID:           userID,
			CompanyID:        companyID,
			Code:             "31006",
		},
		{
			CashflowSubGroup: constants.EQUITY_CAPITAL,
			CashflowGroup:    constants.CASHFLOW_GROUP_FINANCING,
			Category:         constants.CATEGORY_EQUITY,
			Name:             "Simpanan Sukarela",
			Type:             models.EQUITY,
			UserID:           userID,
			CompanyID:        companyID,
			Code:             "31007",
		},
		// Pendapatan
		{
			CashflowSubGroup: constants.ACCEPTANCE_FROM_CUSTOMERS,
			CashflowGroup:    constants.CASHFLOW_GROUP_OPERATING,
			Category:         constants.CATEGORY_OTHER_INCOME,
			Name:             "Pendapatan Mudharabah",
			Type:             models.INCOME,
			UserID:           userID,
			CompanyID:        companyID,
			Code:             "41001",
		},
		{
			CashflowSubGroup: constants.ACCEPTANCE_FROM_CUSTOMERS,
			CashflowGroup:    constants.CASHFLOW_GROUP_OPERATING,
			Category:         constants.CATEGORY_OTHER_INCOME,
			Name:             "Pendapatan Murabahah",
			Type:             models.INCOME,
			UserID:           userID,
			CompanyID:        companyID,
			Code:             "41002",
		},
		{
			CashflowSubGroup: constants.ACCEPTANCE_FROM_CUSTOMERS,
			CashflowGroup:    constants.CASHFLOW_GROUP_OPERATING,
			Category:         constants.CATEGORY_OTHER_INCOME,
			Name:             "Pendapatan Administrasi",
			Type:             models.INCOME,
			UserID:           userID,
			CompanyID:        companyID,
			Code:             "41003",
		},
		{
			CashflowSubGroup: constants.ACCEPTANCE_FROM_CUSTOMERS,
			CashflowGroup:    constants.CASHFLOW_GROUP_OPERATING,
			Category:         constants.CATEGORY_OTHER_INCOME,
			Name:             "Pendapatan Qardh Hasan",
			Type:             models.INCOME,
			UserID:           userID,
			CompanyID:        companyID,
			Code:             "41004",
		},
		{
			CashflowSubGroup: constants.ACCEPTANCE_FROM_CUSTOMERS,
			CashflowGroup:    constants.CASHFLOW_GROUP_OPERATING,
			Category:         constants.CATEGORY_OTHER_INCOME,
			Name:             "Pendapatan Lainnya",
			Type:             models.INCOME,
			UserID:           userID,
			CompanyID:        companyID,
			Code:             "41005",
		},
		{
			CashflowSubGroup: constants.ACCEPTANCE_FROM_CUSTOMERS,
			CashflowGroup:    constants.CASHFLOW_GROUP_OPERATING,
			Category:         constants.CATEGORY_OTHER_INCOME,
			Name:             "Pendapatan Zakat",
			Type:             models.INCOME,
			UserID:           userID,
			CompanyID:        companyID,
			Code:             "41006",
		},
		{
			CashflowSubGroup: constants.ACCEPTANCE_FROM_CUSTOMERS,
			CashflowGroup:    constants.CASHFLOW_GROUP_OPERATING,
			Category:         constants.CATEGORY_OTHER_INCOME,
			Name:             "Pendapatan Infaq",
			Type:             models.INCOME,
			UserID:           userID,
			CompanyID:        companyID,
			Code:             "41007",
		},
		{
			CashflowSubGroup: constants.ACCEPTANCE_FROM_CUSTOMERS,
			CashflowGroup:    constants.CASHFLOW_GROUP_OPERATING,
			Category:         constants.CATEGORY_OTHER_INCOME,
			Name:             "Pendapatan Sadaqah",
			Type:             models.INCOME,
			UserID:           userID,
			CompanyID:        companyID,
			Code:             "41008",
		},
		{
			CashflowSubGroup: constants.ACCEPTANCE_FROM_CUSTOMERS,
			CashflowGroup:    constants.CASHFLOW_GROUP_OPERATING,
			Category:         constants.CATEGORY_OTHER_INCOME,
			Name:             "Penerimaan Dana ZIS",
			Type:             models.INCOME,
			UserID:           userID,
			CompanyID:        companyID,
			Code:             "41009",
		},
		{
			CashflowSubGroup: constants.ACCEPTANCE_FROM_CUSTOMERS,
			CashflowGroup:    constants.CASHFLOW_GROUP_OPERATING,
			Category:         constants.CATEGORY_OTHER_INCOME,
			Name:             "Penyaluran Dana ZIS",
			Type:             models.INCOME,
			UserID:           userID,
			CompanyID:        companyID,
			Code:             "41010",
		},
		{
			CashflowSubGroup: constants.ACCEPTANCE_FROM_CUSTOMERS,
			CashflowGroup:    constants.CASHFLOW_GROUP_OPERATING,
			Category:         constants.CATEGORY_OTHER_INCOME,
			Name:             "Pendapatan Biaya Admin",
			Type:             models.INCOME,
			UserID:           userID,
			CompanyID:        companyID,
			Code:             "41011",
		},
		// Pengeluaran
		{
			CashflowSubGroup: constants.OPERATIONAL_EXPENSES,
			CashflowGroup:    constants.CASHFLOW_GROUP_OPERATING,
			Category:         constants.CATEGORY_EXPENSE,
			Name:             "Beban Administrasi",
			Type:             models.EXPENSE,
			UserID:           userID,
			CompanyID:        companyID,
			Code:             "51001",
		},
		{
			CashflowSubGroup: constants.OPERATIONAL_EXPENSES,
			CashflowGroup:    constants.CASHFLOW_GROUP_OPERATING,
			Category:         constants.CATEGORY_EXPENSE,
			Name:             "Beban Utilitas",
			Type:             models.EXPENSE,
			UserID:           userID,
			CompanyID:        companyID,
			Code:             "51002",
		},

		{
			CashflowSubGroup: constants.OPERATIONAL_EXPENSES,
			CashflowGroup:    constants.CASHFLOW_GROUP_OPERATING,
			Category:         constants.CATEGORY_EXPENSE,
			Name:             "Beban Transportasi",
			Type:             models.EXPENSE,
			UserID:           userID,
			CompanyID:        companyID,
			Code:             "51003",
		},
		{
			CashflowSubGroup: constants.OPERATIONAL_EXPENSES,
			CashflowGroup:    constants.CASHFLOW_GROUP_OPERATING,
			Category:         constants.CATEGORY_EXPENSE,
			Name:             "Beban Bagi Hasil Mudharabah",
			Type:             models.EXPENSE,
			UserID:           userID,
			CompanyID:        companyID,
			Code:             "51004",
		},
		{
			CashflowSubGroup: constants.OPERATIONAL_EXPENSES,
			CashflowGroup:    constants.CASHFLOW_GROUP_OPERATING,
			Category:         constants.CATEGORY_EXPENSE,
			Name:             "Beban Penyusutan",
			Type:             models.EXPENSE,
			UserID:           userID,
			CompanyID:        companyID,
			Code:             "51005",
		},
		{
			CashflowSubGroup: constants.OPERATIONAL_EXPENSES,
			CashflowGroup:    constants.CASHFLOW_GROUP_OPERATING,
			Category:         constants.CATEGORY_EXPENSE,
			Name:             "Beban Lainnya",
			Type:             models.EXPENSE,
			UserID:           userID,
			CompanyID:        companyID,
			Code:             "51006",
		},
		{
			CashflowSubGroup: constants.OPERATIONAL_EXPENSES,
			CashflowGroup:    constants.CASHFLOW_GROUP_OPERATING,
			Category:         constants.CATEGORY_EXPENSE,
			Name:             "Beban Penyaluran Zakat",
			Type:             models.EXPENSE,
			UserID:           userID,
			CompanyID:        companyID,
			Code:             "51007",
		},
		{
			CashflowSubGroup: constants.OPERATIONAL_EXPENSES,
			CashflowGroup:    constants.CASHFLOW_GROUP_OPERATING,
			Category:         constants.CATEGORY_EXPENSE,
			Name:             "Beban Penyaluran Infaq",
			Type:             models.EXPENSE,
			UserID:           userID,
			CompanyID:        companyID,
			Code:             "51008",
		},
		{
			CashflowSubGroup: constants.OPERATIONAL_EXPENSES,
			CashflowGroup:    constants.CASHFLOW_GROUP_OPERATING,
			Category:         constants.CATEGORY_EXPENSE,
			Name:             "Beban Penyaluran Sadaqah",
			Type:             models.EXPENSE,
			UserID:           userID,
			CompanyID:        companyID,
			Code:             "51009",
		},
	}

	accounts = append(accounts, c.netSurplusAccounts(userID, companyID)...)

	// for i := range accounts {
	// 	accounts[i].ConvertTerm()
	// }

	return accounts
}

func (c *CooperativeService) CooperationAccountsTemplate(userID, companyID *string) []models.AccountModel {
	accounts := []models.AccountModel{
		{
			CashflowSubGroup: constants.CASH_BANK,
			CashflowGroup:    constants.CASHFLOW_GROUP_CURRENT_ASSET,
			Category:         constants.CATEGORY_CURRENT_ASSET,
			Name:             "Kas",
			Type:             models.ASSET,
			UserID:           userID,
			CompanyID:        companyID,
			Code:             "11001",
		},
		{
			CashflowSubGroup: constants.CASH_BANK,
			CashflowGroup:    constants.CASHFLOW_GROUP_CURRENT_ASSET,
			Category:         constants.CATEGORY_CURRENT_ASSET,
			Name:             "Bank",
			Type:             models.ASSET,
			UserID:           userID,
			CompanyID:        companyID,
			Code:             "11002",
		},
		{
			CashflowSubGroup: constants.ACCEPTANCE_FROM_CUSTOMERS,
			CashflowGroup:    constants.CASHFLOW_GROUP_OPERATING,
			Category:         constants.CATEGORY_RECEIVABLE,
			Name:             "Piutang Pinjaman",
			Type:             models.RECEIVABLE,
			UserID:           userID,
			CompanyID:        companyID,
			Code:             "11003",
		},
		{
			CashflowSubGroup: constants.ACCEPTANCE_FROM_CUSTOMERS,
			CashflowGroup:    constants.CASHFLOW_GROUP_OPERATING,
			Category:         constants.CATEGORY_RECEIVABLE,
			Name:             "Piutang Bunga",
			Type:             models.RECEIVABLE,
			UserID:           userID,
			CompanyID:        companyID,
			Code:             "11004",
		},
		{
			CashflowSubGroup: constants.ACCEPTANCE_FROM_CUSTOMERS,
			CashflowGroup:    constants.CASHFLOW_GROUP_OPERATING,
			Category:         constants.CATEGORY_RECEIVABLE,
			Name:             "Piutang Lain-lain",
			Type:             models.RECEIVABLE,
			UserID:           userID,
			CompanyID:        companyID,
			Code:             "11005",
		},
		{
			CashflowSubGroup: constants.CASHFLOW_GROUP_FIXED_ASSET,
			CashflowGroup:    constants.CASHFLOW_GROUP_FIXED_ASSET,
			Category:         constants.CATEGORY_FIXED_ASSET,
			Name:             "Aset Tetap",
			Type:             models.ASSET,
			UserID:           userID,
			CompanyID:        companyID,
			Code:             "11007",
		},
		{
			CashflowSubGroup: constants.CASHFLOW_GROUP_DEPRECIATION_AMORTIZATION,
			CashflowGroup:    constants.CASHFLOW_GROUP_FIXED_ASSET,
			Category:         constants.CATEGORY_FIXED_ASSET,
			Name:             "Akumulasi Penyusutan",
			Type:             models.ASSET,
			UserID:           userID,
			CompanyID:        companyID,
			Code:             "11008",
		},
		{
			CashflowSubGroup: constants.CASHFLOW_GROUP_FIXED_ASSET,
			CashflowGroup:    constants.CASHFLOW_GROUP_FIXED_ASSET,
			Category:         constants.CATEGORY_FIXED_ASSET,
			Name:             "Investasi Jangka Panjang",
			Type:             models.ASSET,
			UserID:           userID,
			CompanyID:        companyID,
			Code:             "11009",
		},
		{
			CashflowSubGroup: constants.PAYMENT_TO_VENDORS,
			CashflowGroup:    constants.CASHFLOW_GROUP_OPERATING,
			Category:         constants.CATEGORY_DEBT,
			Name:             "Hutang Bunga Simpanan",
			Type:             models.LIABILITY,
			UserID:           userID,
			CompanyID:        companyID,
			Code:             "21001",
		},
		{
			CashflowSubGroup: constants.PAYMENT_TO_VENDORS,
			CashflowGroup:    constants.CASHFLOW_GROUP_OPERATING,
			Category:         constants.CATEGORY_DEBT,
			Name:             "Hutang Jangka Pendek",
			Type:             models.LIABILITY,
			UserID:           userID,
			CompanyID:        companyID,
			Code:             "21002",
		},
		{
			CashflowSubGroup: constants.PAYMENT_TO_VENDORS,
			CashflowGroup:    constants.CASHFLOW_GROUP_OPERATING,
			Category:         constants.CATEGORY_DEBT,
			Name:             "Hutang Operasional",
			Type:             models.LIABILITY,
			UserID:           userID,
			CompanyID:        companyID,
			Code:             "21003",
		},
		{
			CashflowSubGroup: constants.PAYMENT_TO_VENDORS,
			CashflowGroup:    constants.CASHFLOW_GROUP_OPERATING,
			Category:         constants.CATEGORY_DEBT,
			Name:             "Hutang Jangka Panjang",
			Type:             models.LIABILITY,
			UserID:           userID,
			CompanyID:        companyID,
			Code:             "21004",
		},
		{
			CashflowSubGroup: constants.EQUITY_CAPITAL,
			CashflowGroup:    constants.CASHFLOW_GROUP_FINANCING,
			Category:         constants.CATEGORY_EQUITY,
			Name:             "Simpanan Pokok",
			Type:             models.EQUITY,
			UserID:           userID,
			CompanyID:        companyID,
			Code:             "31001",
		},
		{
			CashflowSubGroup: constants.EQUITY_CAPITAL,
			CashflowGroup:    constants.CASHFLOW_GROUP_FINANCING,
			Category:         constants.CATEGORY_EQUITY,
			Name:             "Simpanan Wajib",
			Type:             models.EQUITY,
			UserID:           userID,
			CompanyID:        companyID,
			Code:             "31002",
		},
		{
			CashflowSubGroup: constants.EQUITY_CAPITAL,
			CashflowGroup:    constants.CASHFLOW_GROUP_FINANCING,
			Category:         constants.CATEGORY_EQUITY,
			Name:             "Simpanan Sukarela",
			Type:             models.EQUITY,
			UserID:           userID,
			CompanyID:        companyID,
			Code:             "31003",
		},

		{
			CashflowSubGroup: constants.EQUITY_CAPITAL,
			CashflowGroup:    constants.CASHFLOW_GROUP_FINANCING,
			Category:         constants.CATEGORY_EQUITY,
			Name:             "Sisa Hasil Usaha (SHU) yang Belum Dibagi",
			Type:             models.EQUITY,
			UserID:           userID,
			CompanyID:        companyID,
			Code:             "31005",
		},
		{
			CashflowSubGroup: constants.ACCEPTANCE_FROM_CUSTOMERS,
			CashflowGroup:    constants.CASHFLOW_GROUP_OPERATING,
			Category:         constants.CATEGORY_SALES,
			Name:             "Pendapatan Bunga Pinjaman",
			Type:             models.INCOME,
			UserID:           userID,
			CompanyID:        companyID,
			Code:             "41001",
		},
		{
			CashflowSubGroup: constants.ACCEPTANCE_FROM_CUSTOMERS,
			CashflowGroup:    constants.CASHFLOW_GROUP_OPERATING,
			Category:         constants.CATEGORY_SALES,
			Name:             "Pendapatan Administrasi",
			Type:             models.INCOME,
			UserID:           userID,
			CompanyID:        companyID,
			Code:             "41002",
		},
		{
			CashflowSubGroup: constants.ACCEPTANCE_FROM_CUSTOMERS,
			CashflowGroup:    constants.CASHFLOW_GROUP_OPERATING,
			Category:         constants.CATEGORY_SALES,
			Name:             "Pendapatan Jasa Lainnya",
			Type:             models.INCOME,
			UserID:           userID,
			CompanyID:        companyID,
			Code:             "41003",
		},
		{
			CashflowSubGroup: constants.ACCEPTANCE_FROM_CUSTOMERS,
			CashflowGroup:    constants.CASHFLOW_GROUP_OPERATING,
			Category:         constants.CATEGORY_SALES,
			Name:             "Pendapatan Investasi",
			Type:             models.INCOME,
			UserID:           userID,
			CompanyID:        companyID,
			Code:             "41004",
		},
		{
			CashflowSubGroup: constants.ACCEPTANCE_FROM_CUSTOMERS,
			CashflowGroup:    constants.CASHFLOW_GROUP_OPERATING,
			Category:         constants.CATEGORY_SALES,
			Name:             "Pendapatan Penjualan Barang - Anggota",
			Type:             models.INCOME,
			UserID:           userID,
			CompanyID:        companyID,
			Code:             "41005",
		},
		{
			CashflowSubGroup: constants.ACCEPTANCE_FROM_CUSTOMERS,
			CashflowGroup:    constants.CASHFLOW_GROUP_OPERATING,
			Category:         constants.CATEGORY_SALES,
			Name:             "Pendapatan Penjualan Barang - Non-Anggota",
			Type:             models.INCOME,
			UserID:           userID,
			CompanyID:        companyID,
			Code:             "41006",
		},
		{
			CashflowSubGroup: constants.ACCEPTANCE_FROM_CUSTOMERS,
			CashflowGroup:    constants.CASHFLOW_GROUP_OPERATING,
			Category:         constants.CATEGORY_OTHER_INCOME,
			Name:             "Pendapatan Biaya Admin",
			Type:             models.INCOME,
			UserID:           userID,
			CompanyID:        companyID,
			Code:             "41011",
		},
		{
			CashflowSubGroup: constants.OPERATIONAL_EXPENSES,
			CashflowGroup:    constants.CASHFLOW_GROUP_OPERATING,
			Category:         constants.CATEGORY_EXPENSE,
			Name:             "Beban Bunga Simpanan",
			Type:             models.EXPENSE,
			UserID:           userID,
			CompanyID:        companyID,
			Code:             "51001",
		},
		{
			CashflowSubGroup: constants.OPERATIONAL_EXPENSES,
			CashflowGroup:    constants.CASHFLOW_GROUP_OPERATING,
			Category:         constants.CATEGORY_EXPENSE,
			Name:             "Beban Administrasi",
			Type:             models.EXPENSE,
			UserID:           userID,
			CompanyID:        companyID,
			Code:             "51002",
		},
		{
			CashflowSubGroup: constants.OPERATIONAL_EXPENSES,
			CashflowGroup:    constants.CASHFLOW_GROUP_OPERATING,
			Category:         constants.CATEGORY_EXPENSE,
			Name:             "Beban Gaji dan Tunjangan",
			Type:             models.EXPENSE,
			UserID:           userID,
			CompanyID:        companyID,
			Code:             "51003",
		},
		{
			CashflowSubGroup: constants.ACQUISITION_SALE_OF_ASSETS,
			CashflowGroup:    constants.CASHFLOW_GROUP_INVESTING,
			Category:         constants.CATEGORY_EXPENSE,
			Name:             "Beban Penyusutan",
			Type:             models.EXPENSE,
			UserID:           userID,
			CompanyID:        companyID,
			Code:             "51004",
		},
		{
			CashflowSubGroup: constants.OPERATIONAL_EXPENSES,
			CashflowGroup:    constants.CASHFLOW_GROUP_OPERATING,
			Category:         constants.CATEGORY_COST_OF_REVENUE,
			Name:             "Beban Operasional Lainnya",
			Type:             models.COST,
			UserID:           userID,
			CompanyID:        companyID,
			Code:             "61001",
		},
		{
			CashflowSubGroup: constants.OPERATIONAL_EXPENSES,
			CashflowGroup:    constants.CASHFLOW_GROUP_OPERATING,
			Category:         constants.CATEGORY_COST_OF_REVENUE,
			Name:             "Beban Operasional Penjualan",
			Type:             models.COST,
			UserID:           userID,
			CompanyID:        companyID,
			Code:             "61002",
		},
	}
	accounts = append(accounts, c.netSurplusAccounts(userID, companyID)...)

	// for i := range accounts {
	// 	accounts[i].ConvertTerm()
	// }

	return accounts
}

func (c *CooperativeService) netSurplusAccounts(userID, companyID *string) []models.AccountModel {
	return []models.AccountModel{
		{
			CashflowSubGroup: constants.OTHER_INVESTMENT_ACTIVITIES,
			CashflowGroup:    constants.CASHFLOW_GROUP_INVESTING,
			Category:         constants.CATEGORY_EQUITY,

			Name:      "Cadangan Koperasi",
			Type:      constants.TYPE_EQUITY,
			UserID:    userID,
			CompanyID: companyID,
			Code:      "33001",
		},
		{
			CashflowSubGroup: constants.OPERATIONAL_EXPENSES,
			CashflowGroup:    constants.CASHFLOW_GROUP_OPERATING,
			Category:         constants.CATEGORY_EQUITY,

			Name:      "Dana Pendidikan",
			Type:      constants.TYPE_EQUITY,
			UserID:    userID,
			CompanyID: companyID,
			Code:      "33002",
		},
		{
			CashflowSubGroup: constants.OPERATIONAL_EXPENSES,
			CashflowGroup:    constants.CASHFLOW_GROUP_OPERATING,
			Category:         constants.CATEGORY_EQUITY,

			Name:      "Dana Sosial",
			Type:      constants.TYPE_EQUITY,
			UserID:    userID,
			CompanyID: companyID,
			Code:      "33003",
		},
		{
			CashflowSubGroup: constants.OTHER_CURRENT_ASSETS,
			CashflowGroup:    constants.CASHFLOW_GROUP_OPERATING,
			Category:         constants.CATEGORY_EQUITY,

			Name:      "Jasa Usaha",
			Type:      constants.TYPE_EQUITY,
			UserID:    userID,
			CompanyID: companyID,
			Code:      "33004",
		},
		{
			CashflowSubGroup: constants.EQUITY_CAPITAL,
			CashflowGroup:    constants.CASHFLOW_GROUP_FINANCING,
			Category:         constants.CATEGORY_EQUITY,

			Name:      "Jasa Modal",
			Type:      constants.TYPE_EQUITY,
			UserID:    userID,
			CompanyID: companyID,
			Code:      "33005",
		},
		{
			CashflowSubGroup: constants.OPERATIONAL_EXPENSES,
			CashflowGroup:    constants.CASHFLOW_GROUP_OPERATING,
			Category:         constants.CATEGORY_EQUITY,

			Name:      "Dana Pengurus",
			Type:      constants.TYPE_EQUITY,
			UserID:    userID,
			CompanyID: companyID,
			Code:      "33006",
		},
		{
			CashflowSubGroup: constants.OPERATIONAL_EXPENSES,
			CashflowGroup:    constants.CASHFLOW_GROUP_OPERATING,
			Category:         constants.CATEGORY_EQUITY,

			Name:      "Dana Lainnya",
			Type:      constants.TYPE_EQUITY,
			UserID:    userID,
			CompanyID: companyID,
			Code:      "33007",
		},

		{
			CashflowSubGroup: constants.OTHER_CURRENT_ASSETS,
			CashflowGroup:    constants.CASHFLOW_GROUP_OPERATING,
			Category:         constants.CATEGORY_DEBT,

			Name:      "Hutang SHU Ke Anggota",
			Type:      constants.TYPE_LIABILITY,
			UserID:    userID,
			CompanyID: companyID,
			Code:      "23004",
		},

		{
			CashflowSubGroup: constants.OPERATIONAL_EXPENSES,
			CashflowGroup:    constants.CASHFLOW_GROUP_OPERATING,
			Category:         constants.CATEGORY_EXPENSE,

			Name:      "Beban Sosial",
			Type:      constants.TYPE_EXPENSE,
			UserID:    userID,
			CompanyID: companyID,
			Code:      "53001",
		},
		{
			CashflowSubGroup: constants.OPERATIONAL_EXPENSES,
			CashflowGroup:    constants.CASHFLOW_GROUP_OPERATING,
			Category:         constants.CATEGORY_EXPENSE,

			Name:      "Beban Pendidikan",
			Type:      constants.TYPE_EXPENSE,
			UserID:    userID,
			CompanyID: companyID,
			Code:      "53001",
		},
		{
			CashflowSubGroup: constants.CASH_BANK,
			CashflowGroup:    constants.CASHFLOW_GROUP_CURRENT_ASSET,
			Category:         constants.CATEGORY_CURRENT_ASSET,

			Name:      "Kas Khusus Alokasi SHU",
			Type:      constants.TYPE_ASSET,
			UserID:    userID,
			CompanyID: companyID,
			Code:      "13001",
		},
		{
			CashflowSubGroup: constants.CASH_BANK,
			CashflowGroup:    constants.CASHFLOW_GROUP_CURRENT_ASSET,
			Category:         constants.CATEGORY_CURRENT_ASSET,

			Name:      "Kas Alokasi SHU Jasa Usaha",
			Type:      constants.TYPE_ASSET,
			UserID:    userID,
			CompanyID: companyID,
			Code:      "13002",
		},
		{
			CashflowSubGroup: constants.CASH_BANK,
			CashflowGroup:    constants.CASHFLOW_GROUP_CURRENT_ASSET,
			Category:         constants.CATEGORY_CURRENT_ASSET,

			Name:      "Kas Alokasi SHU Jasa Modal",
			Type:      constants.TYPE_ASSET,
			UserID:    userID,
			CompanyID: companyID,
			Code:      "13003",
		},
		{
			CashflowSubGroup: constants.CASH_BANK,
			CashflowGroup:    constants.CASHFLOW_GROUP_CURRENT_ASSET,
			Category:         constants.CATEGORY_CURRENT_ASSET,

			Name:      "Kas Alokasi SHU Dana Sosial",
			Type:      constants.TYPE_ASSET,
			UserID:    userID,
			CompanyID: companyID,
			Code:      "13004",
		},
		{
			CashflowSubGroup: constants.CASH_BANK,
			CashflowGroup:    constants.CASHFLOW_GROUP_CURRENT_ASSET,
			Category:         constants.CATEGORY_CURRENT_ASSET,

			Name:      "Kas Alokasi SHU Dana Pendidikan",
			Type:      constants.TYPE_ASSET,
			UserID:    userID,
			CompanyID: companyID,
			Code:      "13005",
		},
		{
			CashflowSubGroup: constants.CASH_BANK,
			CashflowGroup:    constants.CASHFLOW_GROUP_CURRENT_ASSET,
			Category:         constants.CATEGORY_CURRENT_ASSET,

			Name:      "Kas Alokasi SHU Dana Cadangan",
			Type:      constants.TYPE_ASSET,
			UserID:    userID,
			CompanyID: companyID,
			Code:      "13006",
		},
		{
			CashflowSubGroup: constants.CASH_BANK,
			CashflowGroup:    constants.CASHFLOW_GROUP_CURRENT_ASSET,
			Category:         constants.CATEGORY_CURRENT_ASSET,

			Name:      "Kas Alokasi SHU Dana Pengurus",
			Type:      constants.TYPE_ASSET,
			UserID:    userID,
			CompanyID: companyID,
			Code:      "13007",
		},
	}

}
